FROM {{.Base}}
MAINTAINER {{.Author}}
{{if .Volume}}VOLUME {{.Volume}} {{end}}
{{if .CopyTo}}COPY {{.CopyFrom}} {{.CopyTo}} {{end}}
{{if .RUN}}RUN {{.RUN}} {{end}}
{{if .EntryPoint}}ENTRYPOINT {{.EntryPoint}} {{end}}
{{if .Command}}CMD [{{.Command}}] {{end}}